### ISSUE TITLE
Make "Window Glow" Optional

### ISSUE THREAD

**Issue by rawkode** [paperwm/PaperWM#289]
Is there a way to disable the border around windows?

**Comment by rawkode** [comment]
Maybe a duplicate of #213

**Comment by olejorgenb** [comment]
Yes, use something like this in stylesheet.css:

```css
.paperwm-selection {
    background-color: transparent;
    border: 0px;
}
```

(`display: none` did not work here)
