### ISSUE TITLE
Focused window border is too distracting.

### ISSUE THREAD

**Issue by vvvvvvitor** [paperwm/PaperWM#683]
**Is your feature request related to a problem? Please describe.**
The window focus border is too on the nose and distracting, it also looks kinda weird with the bottom corners having no roundness to them.

**Describe the solution you'd like**
Wouldn't the normal GNOME indicator or similar be enough?

**Describe alternatives you've considered**
There are none.

**Comment by jtaala** [comment]
This comes down to preference (for example, the normal window border isn't apparent enough for most our users' preference, including mine).

Please see the README section for styling the window borders etc.

https://github.com/paperwm/PaperWM#user-configuration--development

For example, here's mine (in `~/.config/paperwm/user.css`:

```css

.paperwm-selection {
    border: 7px rgba(215, 66, 98, 0.8);
    background-color: rgba(0, 0, 0, 0);
}

````

You can see a full list of stylable components here:
https://github.com/paperwm/PaperWM/blob/release/config/user.css

**Comment by jtaala** [comment]
Once made change you can disable/enable PaperWM to apply.

**Comment by jtaala** [comment]
> Wouldn't the normal GNOME indicator or similar be enough?

No, it becomes very hard to tell which window is actually selected in tiling (when they're all lined again next to each other).

But, if you'd prefer the default GNOME indicator (i.e. no border), set this in your `user.css` and disable/enable PaperWM:

```css
.paperwm-selection {
    border: rgba(0 ,0, 0, 0);
    background-color: rgba(0, 0, 0, 0);
}
```
which will make the selected window border and background completely transparent.
